### PR TITLE
Make bloomlibrary tolerant of 'topic:' prefix or no prefix (BL-4284)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary/264)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/modules/common/services.js, line 203 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdW_MvtLAmgpe3mPlGP:-KdW_MvtLAmgpe3mPlGQ:ba579zx) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L203)):*
> ```JavaScript
>         this.sandboxUrl = "https://bloom-parse-server-develop.azurewebsites.net/parse";
>         // This only seems to work with http
>         this.localUrl = "http://localhost:1337/parse";
> ```

So how did it work before? Doesn't seem related to the purpose of the PR. And, one of our 3.9 tasks is for making BL work with https. Will this cause a problem for that?

---

*[src/app/modules/common/services.js, line 378 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdWZAXgJi1rq3Hp5fk_:-KdWZAXgJi1rq3Hp5fka:bs3a7rn) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L378)):*
> ```JavaScript
>         // and whose languages list includes the specified language, if any
>         // and whose tags include the specified tag, if any;
>         // or, if shelf is specified, return exactly the books in that shelf, ignoring other params.
> ```

Is this comment out of date? The method no longer seems to ignore the other params if a shelf is specified.

---

*[src/app/modules/common/services.js, line 418 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdWZcO0eZR3IijiPppY:-KdWZcO0eZR3IijiPppZ:b-8ye2v0) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L418)):*
> ```JavaScript
>                 if (shelfKey) {
>                     query.containsAll("tags", ["bookshelf:" + shelfKey, tag]);
>                 } else {
> ```

We have to deal with uncertainty about whether the tags in the database will have topic:, I think, because (even after you batch-update them) for a long time we will have to deal with old versions of Bloom uploading books with unmarked topics.
But why do we have to deal with the argument passed to this method not having a prefix?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/modules/common/services.js, line 203 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdW_MvtLAmgpe3mPlGP:-KdWbjZVMI2MWAzVxpfh:b-6x8nqb) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L203)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

So how did it work before? Doesn't seem related to the purpose of the PR. And, one of our 3.9 tasks is for making BL work with https. Will this cause a problem for that?
</blockquote></details>

It is likely it didn't work before. It is only for running locally, so it won't affect live deployment.
You're correct that it isn't related to the PR; I can pull it out if you want. It ended up here because I had to change it to run locally in order to make these changes.

---

*[src/app/modules/common/services.js, line 378 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdWZAXgJi1rq3Hp5fk_:-KdX7TfE5Aq1z1GPUyq6:b-au5rwo) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L378)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is this comment out of date? The method no longer seems to ignore the other params if a shelf is specified.
</blockquote></details>

I agree it seems to be inaccurate now. I'll try to clean it up.

---

*[src/app/modules/common/services.js, line 418 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdWZcO0eZR3IijiPppY:-KdX55eNgykzfPyGQWRE:bnykw6x) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L418)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We have to deal with uncertainty about whether the tags in the database will have topic:, I think, because (even after you batch-update them) for a long time we will have to deal with old versions of Bloom uploading books with unmarked topics.
But why do we have to deal with the argument passed to this method not having a prefix?
</blockquote></details>

Actually, the problem of old Blooms is easily solved by a beforeSave function on the server which adds 'topic:' if is missing (which has been done in the PR for the server code).

The problem being solved here is two-fold (and specifically relates to clicking a topic in the sidebar):
1) By handling here whether or not the tag has 'topic:' included, we don't have to worry about trying to coordinate the deployment of this code with the change to the database tags to include 'topic:'.
2) By looking up books with 'topic:' and without, we don't have to worry about trying to coordinate the deployment of this code with the batch update to clean up existing books.

This code provides maximum flexibility such that it will work now, after the tags are updated, after the books are updated, and any mishmash of state between those.

We could revisit this code to simplify it after all the other changes are made.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/modules/common/services.js, line 203 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdW_MvtLAmgpe3mPlGP:-KdX87HJxrXlHiCbnpme:b-ewfx0s) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L203)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It is likely it didn't work before. It is only for running locally, so it won't affect live deployment.
You're correct that it isn't related to the PR; I can pull it out if you want. It ended up here because I had to change it to run locally in order to make these changes.
</blockquote></details>

Since I'm making a change anyway, I'll go ahead and pull this out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264)*

**Comment by andrew-polk** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/modules/common/services.js, line 203 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdW_MvtLAmgpe3mPlGP:-KdXCqM5h42jWf0x2ALV:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L203)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Since I'm making a change anyway, I'll go ahead and pull this out.
</blockquote></details>

Done.

---

*[src/app/modules/common/services.js, line 378 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdWZAXgJi1rq3Hp5fk_:-KdXCq9ScZ4S9hRF95Hn:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L378)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I agree it seems to be inaccurate now. I'll try to clean it up.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264)*

**Comment by JohnThomson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/modules/common/services.js, line 203 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdW_MvtLAmgpe3mPlGP:-KdXjCG_eFqIiZz25RTv:bd67fzw) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L203)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. I was going to say, not a problem if not used in deployment.

---

*[src/app/modules/common/services.js, line 378 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdWZAXgJi1rq3Hp5fk_:-KdXkVp-PXf1GYxCB3MH:b2hz0r9) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L378)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not seeing a change...maybe you didn't push the new commit yet? Anyway that's the last issue and I'm happy to trust you to clean it up nicely.

---

*[src/app/modules/common/services.js, line 418 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdWZcO0eZR3IijiPppY:-KdXjUAocKyk8-9K4Hzh:b-4s8qqi) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L418)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Actually, the problem of old Blooms is easily solved by a beforeSave function on the server which adds 'topic:' if is missing (which has been done in the PR for the server code).

The problem being solved here is two-fold (and specifically relates to clicking a topic in the sidebar):
1) By handling here whether or not the tag has 'topic:' included, we don't have to worry about trying to coordinate the deployment of this code with the change to the database tags to include 'topic:'.
2) By looking up books with 'topic:' and without, we don't have to worry about trying to coordinate the deployment of this code with the batch update to clean up existing books.

This code provides maximum flexibility such that it will work now, after the tags are updated, after the books are updated, and any mishmash of state between those.

We could revisit this code to simplify it after all the other changes are made.
</blockquote></details>

Initially I was thinking, that explains why if (tag.indexOf('topic:') === 0) we look for both things on the server.
But I thought that (tag.indexOf(':') < 0) is only needed to handle the possibility that the tags embedded in this website (which would automatically be deployed at the same time as this code) were missing a prefix. But I guess the list of tags the user can click on is also downloaded dynamically? In which case you are right, and your code is fine. In any case it was a minor quibble; if what you have seems safer let's stick with it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264)*

**Comment by andrew-polk** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/modules/common/services.js, line 418 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264#-KdWZcO0eZR3IijiPppY:-KdkZ7blP9xJBmeTvuZr:b-fehukv) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/df98f76720e408b3c78e2e29f11b51e89f29f76b/src/app/modules/common/services.js#L418)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Initially I was thinking, that explains why if (tag.indexOf('topic:') === 0) we look for both things on the server.
But I thought that (tag.indexOf(':') < 0) is only needed to handle the possibility that the tags embedded in this website (which would automatically be deployed at the same time as this code) were missing a prefix. But I guess the list of tags the user can click on is also downloaded dynamically? In which case you are right, and your code is fine. In any case it was a minor quibble; if what you have seems safer let's stick with it.
</blockquote></details>

Yes, the tags come from the database dynamically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/264)*

**Pull request merged**
