### PR TITLE
Bookshelf links, and automatic bookshelf creation

### PR DESCRIPTION
**Pull request by Aelazr**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary/243)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[parseComCode/main.js, line 253 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-KNIeQIkEVH0fAzpKgCa:-KNIeQIlSJs2o0PUj3d3:1448096062) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/927838e5e73eb52862df1181800ffacf332d59f1/parseComCode/main.js#L253)):*
> ```JavaScript
> });
> 
> Parse.Cloud.afterSave("books", function(request) {
> ```

Is there a requirement to delete bookshelves if the last book or tag for a bookshelf is deleted? Probably not worth it, but just checking if JH had said anything.

---

*[parseComCode/main.js, line 258 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-KNIdvuUASRdC1Z1p9T6:-KNIdvuVu5H9zchfyEOW:-183428474) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/927838e5e73eb52862df1181800ffacf332d59f1/parseComCode/main.js#L258)):*
> ```JavaScript
>         return element.indexOf("bookshelf:") > -1;
>     }).map(function(element) {
>         return element.substr(10);
> ```

Can you make this less fragile? For example, you could make "bookshelf:" a constant bookshelfPrefix and then use bookshelfPrefix.length.

---

*[parseComCode/main.js, line 260 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-KNIeAxNDk16qg-qAA0f:-KNIeAxNDk16qg-qAA0g:1834685008) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/927838e5e73eb52862df1181800ffacf332d59f1/parseComCode/main.js#L260)):*
> ```JavaScript
>         return element.substr(10);
>     }).forEach(function(key) {
>         var Bookshelf = Parse.Object.extend("bookshelf");
> ```

Any reason to capitalize Bookshelf?

---

*[src/app/modules/app/app.js, line 196 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-KNIdUboq8Yiot7y76At:-KNIdUboq8Yiot7y76Au:-1345292347) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/927838e5e73eb52862df1181800ffacf332d59f1/src/app/modules/app/app.js#L196)):*
> ```JavaScript
>                 //Search through otherBookshelves
>                 for(var i = 0; i < $scope.otherBookshelves.length; i++) {
>                     //If the currentLang is in the other list, add it to the top (visible) list
> ```

Not a big deal, but go ahead and update the comment.

---

*[src/app/modules/common/services.js, line 227 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-KNIakQ28TVzlyORm4t9:-KNIakQ28TVzlyORm4tA:1834685008) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/927838e5e73eb52862df1181800ffacf332d59f1/src/app/modules/common/services.js#L227)):*
> ```JavaScript
>             defer = $q.defer(); // used to implement angularjs-style promise
> 
>             var Bookshelf = Parse.Object.extend("bookshelf");
> ```

Any reason to capitalize Bookshelf?

---

*[src/app/modules/common/services.js, line 229 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-KNIaeVTHKATNeZ6muoC:-KNIaeVUoYEfzMMmBj_W:367620956) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/927838e5e73eb52862df1181800ffacf332d59f1/src/app/modules/common/services.js#L229)):*
> ```JavaScript
>             var Bookshelf = Parse.Object.extend("bookshelf");
>             var query = new Parse.Query(Bookshelf);
>             query.descending("englishName");
> ```

Don't you want ascending (A-B-C)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243)*

**Comment by Aelazr** [comment]
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[parseComCode/main.js, line 253 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-KNIeQIkEVH0fAzpKgCa:-KNIgemPkvLSTtGnunAw:-808447927) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/927838e5e73eb52862df1181800ffacf332d59f1/parseComCode/main.js#L253)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Is there a requirement to delete bookshelves if the last book or tag for a bookshelf is deleted? Probably not worth it, but just checking if JH had said anything.
</details>
He never mentioned removing bookshelves

---

*[parseComCode/main.js, line 260 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-KNIeAxNDk16qg-qAA0f:-KNIgK1t4B0BwiQWR6nk:-1898584039) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/927838e5e73eb52862df1181800ffacf332d59f1/parseComCode/main.js#L260)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Any reason to capitalize Bookshelf?
</details>
Bookshelf is not a normal bookshelf instance, it is representative of the parse class. For use with constructing queries, it's how parse documentation names them.

---

*[src/app/modules/common/services.js, line 227 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-KNIakQ28TVzlyORm4t9:-KNIgbytjv4tVMC8ERYs:1351735696) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/927838e5e73eb52862df1181800ffacf332d59f1/src/app/modules/common/services.js#L227)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Any reason to capitalize Bookshelf?
</details>
Same as previous

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243)*

**Comment by Aelazr** [comment]
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[parseComCode/main.js, line 258 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-KNIdvuUASRdC1Z1p9T6:-KNIgsVOSQOSF0XaT-Gd:-499146009) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/927838e5e73eb52862df1181800ffacf332d59f1/parseComCode/main.js#L258)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Can you make this less fragile? For example, you could make "bookshelf:" a constant bookshelfPrefix and then use bookshelfPrefix.length.
</details>
Done.

---

*[src/app/modules/app/app.js, line 196 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-KNIdUboq8Yiot7y76At:-KNIgtjlWIfkMm3yvq0I:-499146009) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/927838e5e73eb52862df1181800ffacf332d59f1/src/app/modules/app/app.js#L196)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Not a big deal, but go ahead and update the comment.
</details>
Done.

---

*[src/app/modules/common/services.js, line 229 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-KNIaeVTHKATNeZ6muoC:-KNIguGlUvHLqcqzf5pF:-499146009) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/927838e5e73eb52862df1181800ffacf332d59f1/src/app/modules/common/services.js#L229)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Don't you want ascending (A-B-C)?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/243#-:-KNIhCLzYHnAs-D3I8St:1417088721)*

**Pull request merged**
