### PR TITLE
Sample batch operation script that assigns tags based on a regex for a books attribute

### PR DESCRIPTION
**Pull request by Aelazr**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary/244)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KNrqXh5r60GJwLPO1wN:-KNrqXh5r60GJwLPO1wO:-958307245) (no related file):*
Unless I'm not thinking clearly, the assignTagToBooks function belongs in AssignTags.js and most of the code in AssignTags (argument and flow logic) belongs in BatchServices.js.

---

*[parseComCode/BatchOperations/BatchServices.js, line 4 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KNrmckOchsXLu95wyNM:-KNrmckPWqUSGRskQXAd:349391370) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/3a733bf118b48661959acd56ee87959324c914c2/parseComCode/BatchOperations/BatchServices.js#L4)):*
> ```JavaScript
> 
> var hostname = "api.parse.com";
> var headers = {
> ```

Should there be a command line argument for selecting which instance to use?

---

*[parseComCode/BatchOperations/BatchServices.js, line 24 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KNrnZayi9I8LODtGznD:-KNrnZayi9I8LODtGznE:78156646) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/3a733bf118b48661959acd56ee87959324c914c2/parseComCode/BatchOperations/BatchServices.js#L24)):*
> ```JavaScript
>                 resolve(username);
>        	    } else {
>                 console.log("To update object(s) requires a logged in user that has permissions to modify the object, if in doubt, check the ACL and CLP.");
> ```

Perhaps nitpicking, but this should be "object. If in doubt"

---

*[parseComCode/BatchOperations/BatchServices.js, line 44 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KNrnqz_kMZnZ6lWt6Ot:-KNrnqz_kMZnZ6lWt6Ou:-1103978829) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/3a733bf118b48661959acd56ee87959324c914c2/parseComCode/BatchOperations/BatchServices.js#L44)):*
> ```JavaScript
>                                 break;
>                             default:
>                                 process.stdout.write("\033[2K\033[200D" + query);
> ```

Warrants a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244)*

**Comment by Aelazr** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KNrqXh5r60GJwLPO1wN:-KNrvfMoZFurscqf0pA8:1008558090) (no related file):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Unless I'm not thinking clearly, the assignTagToBooks function belongs in AssignTags.js and most of the code in AssignTags (argument and flow logic) belongs in BatchServices.js.
</details>
I'm having a little bit of trouble wrapping my mind around that one. I think I understand what you are getting, so correct me if I'm wrong. All batch operations will follow the same flow, have similar arguments, all operating on the books class. The only difference being in how the books objects are modified?

---

*[parseComCode/BatchOperations/BatchServices.js, line 4 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KNrmckOchsXLu95wyNM:-KNrwTgCcyq7FvUnh5GV:1050824552) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/3a733bf118b48661959acd56ee87959324c914c2/parseComCode/BatchOperations/BatchServices.js#L4)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Should there be a command line argument for selecting which instance to use?
</details>
I'll add that. Is the hostname going to change with moving to ParseServer?

---

*[parseComCode/BatchOperations/BatchServices.js, line 24 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KNrnZayi9I8LODtGznD:-KNrwowYGdVfTgWERVRb:-499146009) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/3a733bf118b48661959acd56ee87959324c914c2/parseComCode/BatchOperations/BatchServices.js#L24)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Perhaps nitpicking, but this should be "object. If in doubt"
</details>
Done.

---

*[parseComCode/BatchOperations/BatchServices.js, line 44 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KNrnqz_kMZnZ6lWt6Ot:-KNrwpmnYlt7vHizR9Rd:-499146009) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/3a733bf118b48661959acd56ee87959324c914c2/parseComCode/BatchOperations/BatchServices.js#L44)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Warrants a comment.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244)*

**Comment by andrew-polk** [comment]
*[parseComCode/BatchOperations/BatchServices.js, line 4 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KNrmckOchsXLu95wyNM:-KNs2Ic8Spcue9bgqoMn:-588937464) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/3a733bf118b48661959acd56ee87959324c914c2/parseComCode/BatchOperations/BatchServices.js#L4)):*
<details><summary><i>Previously, Aelazr (Azrael Brown) wrote…</i></summary>
> I'll add that. Is the hostname going to change with moving to ParseServer?
</details>
Probably, but I think that is fine being hard-coded. We will have to change other code at that time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244)*

**Comment by Aelazr** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[parseComCode/BatchOperations/BatchServices.js, line 4 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KNrmckOchsXLu95wyNM:-KNs309I4GnVxQe2rEFN:-499146009) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/3a733bf118b48661959acd56ee87959324c914c2/parseComCode/BatchOperations/BatchServices.js#L4)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Probably, but I think that is fine being hard-coded. We will have to change other code at that time.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KNrqXh5r60GJwLPO1wN:-KNs315N3Ke4TUDf008w:666484835) (no related file):*
<details><summary><i>Previously, Aelazr (Azrael Brown) wrote…</i></summary>
> I'm having a little bit of trouble wrapping my mind around that one. I think I understand what you are getting, so correct me if I'm wrong. All batch operations will follow the same flow, have similar arguments, all operating on the books class. The only difference being in how the books objects are modified?
</details>
Extract as much as you can. I think the flow (i, l, or f) should definitely be common code if possible. If you can at least extract that part, it would be good. 
We shouldn't assume all scripts will operate on books, so don't extract that specifically, but see if you can make it generic. Have you used the concept of delegate functions before? I think that would be one way to achieve this.

I'm not sure how much to push back because I don't think this is worth a ton of extra effort, but I think it would definitely be better code if the control logic was all common and only the specific queries and puts were in AssignTags.

If it's not clear what I'm saying or you want to look into it together, we can get in Hangouts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[parseComCode/BatchOperations/BatchOperation.js, line 144 \[r4\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KO5eC7ecOsWwCanOZDg:-KO5eC7ecOsWwCanOZDh:-533555486) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/67cac8f0cfa7f3d01715665236c3fa2fa96d2dda/parseComCode/BatchOperations/BatchOperation.js#L144)):*
> ```JavaScript
> 
> //Fetches objects matching the <regex> on <attribute> from Parse
> findObjects = function (attr, regex) {
> ```

Passing in attr and never using it, but using attribute (the passed in value) below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 2 files at r5.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[parseComCode/BatchOperations/BatchOperation.js, line 144 \[r4\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KO5eC7ecOsWwCanOZDg:-KOLX1qQJz4ZAUJGgiYm:-1036875764) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/67cac8f0cfa7f3d01715665236c3fa2fa96d2dda/parseComCode/BatchOperations/BatchOperation.js#L144)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Passing in attr and never using it, but using attribute (the passed in value) below.
</details>
I probably should have written that better. Here, the function takes a parameter called 'attr'. That parameter is never used. Within the function, you are using 'attribute' which is a global variable. If you're going to continue to use the global variable, remove the unused parameter.

---

*[parseComCode/BatchOperations/README.md, line 46 \[r5\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KOLXgE-F5kxfj7pfcxH:-KOLXgE-F5kxfj7pfcxI:660984864) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/3c8af7091e3afb7002c0ee0abcecb09e146b5aea/parseComCode/BatchOperations/README.md#L46)):*
> ```Markdown
> * Create a new .js file for the operation
> * Require BatchOperation.js
> * Replace the properties usageAddendum, classBeingBatchUpdated and classAttributesToPreview on BatchOperation
> ```

Rather than 'replace', I think override or set would communicate more clearly. Same for statement below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244)*

**Comment by Aelazr** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KNrqXh5r60GJwLPO1wN:-KOL_9lYQcH1AMeBb0ti:-499146009) (no related file):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Extract as much as you can. I think the flow (i, l, or f) should definitely be common code if possible. If you can at least extract that part, it would be good. 
> We shouldn't assume all scripts will operate on books, so don't extract that specifically, but see if you can make it generic. Have you used the concept of delegate functions before? I think that would be one way to achieve this.
> 
> I'm not sure how much to push back because I don't think this is worth a ton of extra effort, but I think it would definitely be better code if the control logic was all common and only the specific queries and puts were in AssignTags.
> 
> If it's not clear what I'm saying or you want to look into it together, we can get in Hangouts.
</details>
Done.

---

*[parseComCode/BatchOperations/BatchOperation.js, line 144 \[r4\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KO5eC7ecOsWwCanOZDg:-KOLZvzykfmPbV8ZIr8O:-499146009) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/67cac8f0cfa7f3d01715665236c3fa2fa96d2dda/parseComCode/BatchOperations/BatchOperation.js#L144)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> I probably should have written that better. Here, the function takes a parameter called 'attr'. That parameter is never used. Within the function, you are using 'attribute' which is a global variable. If you're going to continue to use the global variable, remove the unused parameter.
</details>
Done.

---

*[parseComCode/BatchOperations/README.md, line 46 \[r5\]](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-KOLXgE-F5kxfj7pfcxH:-KOLZxvPeke1PO3rP0jL:-499146009) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/3c8af7091e3afb7002c0ee0abcecb09e146b5aea/parseComCode/BatchOperations/README.md#L46)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Rather than 'replace', I think override or set would communicate more clearly. Same for statement below.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/244#-:-KOLaHzsq06waETDD_Vv:1417088721)*

**Pull request merged**
