### PR TITLE
BL-5091 enable indented (sub) bookshelves

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary/277)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/modules/browse/browse-controller.js, line 211 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/277#-KwGJmkgMbnX92O9bR_-:-KwGJmkhG9F0msuKcGBx:b-y3nsuq) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/d35429d298c502528a0500b749762fd90469e0fd/src/app/modules/browse/browse-controller.js#L211)):*
> ```JavaScript
>                 // We need to retrieve the shelf object, and we can't run the query to get the count
>                 // until we get the result.
>                 bookService.getBookshelf($scope.shelfKey).then(function (shelf) {
> ```

I'm not seeing how your change makes this unnecessary. Or was it already unnecessary before your change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/277)*

**Comment by andrew-polk** [comment]
Also, the issue number is wrong on the commit (should be 5091). I corrected it on the PR summary.

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/modules/browse/browse-controller.js, line 211 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/277#-KwGJmkgMbnX92O9bR_-:-KwGfkzrsHeQtUYv8TdY:b-nbqhz9) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/d35429d298c502528a0500b749762fd90469e0fd/src/app/modules/browse/browse-controller.js#L211)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not seeing how your change makes this unnecessary. Or was it already unnecessary before your change?
</blockquote></details>

As far as I could see, it was already unnecessary. The result we waited for was not used. I'm not sure whether the simplified logic was necessary for this change, but it simplified at least the process of figuring out what I needed to do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/277)*

**Comment by JohnThomson** [comment]
Fixed, sorry.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/277#-:-KwGgoe0kNCFc0FwfHsq:bn65nx0)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/277#-:-KwGxtoUONRj6Fw-jtf8:bnfp4nl)*

**Pull request merged**
