### PR TITLE
Enhance BloomLibrary build process (BL-4205)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
1) rename *.jade to *.pug
2) compile pug files in grunt (automatically under "grunt watch")

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary/261)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitignore, line 8 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261#-Kd2bTYo85ZVP7_LEjiE:-Kd2bTYo85ZVP7_LEjiF:bllrmg3) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/ddda34aca38ac3283ebadc9c1d2a43b5e11ddbea/.gitignore#L8)):*
> ```
> vendor/
> .idea/*
> src/app/modules/prefs/prefs.tpl.html
> ```

I guess you had to list them individually because src/app/modules/**/*.tpl.html was too inclusive?

---

*[Gruntfile.js, line 323 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261#-Kd2c2l-fPMEF1z1G4h3:-Kd2c2l-fPMEF1z1G4h4:b-8scbri) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/ddda34aca38ac3283ebadc9c1d2a43b5e11ddbea/Gruntfile.js#L323)):*
> ```JavaScript
>         },
>         files: {
>           'src/app/modules/prefs/prefs.tpl.html': 'src/app/modules/prefs/prefs.tpl.pug',
> ```

Does this mean we will have to add a line here if we add a new pug file?

---

*[src/app/modules/static/about.tpl.pug, line 4 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261#-Kd2cfo8OOOLIK99-cA2:-Kd2cfo8OOOLIK99-cA3:b-nqcrrf) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/ddda34aca38ac3283ebadc9c1d2a43b5e11ddbea/src/app/modules/static/about.tpl.pug#L4)):*
> ```Pug
> 	p
> 		=name
> 		|&nbsp;(
> ```

I'm surprised this doesn't need to be 
```
| &nbsp;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitignore, line 8 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261#-Kd2bTYo85ZVP7_LEjiE:-Kd2duCKV9RYo82KUZGI:b-l37vup) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/ddda34aca38ac3283ebadc9c1d2a43b5e11ddbea/.gitignore#L8)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess you had to list them individually because src/app/modules/**/*.tpl.html was too inclusive?
</blockquote></details>

yes, there are a number of *.tpl.html files that don't have a corresponding pug/jade file.

---

*[Gruntfile.js, line 323 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261#-Kd2c2l-fPMEF1z1G4h3:-Kd2e1Jz1F-8ZcPNl_-e:b-sau3kl) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/ddda34aca38ac3283ebadc9c1d2a43b5e11ddbea/Gruntfile.js#L323)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does this mean we will have to add a line here if we add a new pug file?
</blockquote></details>

Alas, I'm afraid that's the case, unless we add new pug files for all existing *.tpl.html files.  Then we might be able to simplify things...

---

*[src/app/modules/static/about.tpl.pug, line 4 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261#-Kd2cfo8OOOLIK99-cA2:-Kd2eI20hJs61Rsq5R5h:b-u8zs9h) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/ddda34aca38ac3283ebadc9c1d2a43b5e11ddbea/src/app/modules/static/about.tpl.pug#L4)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm surprised this doesn't need to be 
```
| &nbsp;
```
</blockquote></details>

Maybe there should be a space there, but it compiled.  I'll add a space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261)*

**Comment by andrew-polk** [comment]
Request for comment. Otherwise, :lgtm: 

---

Reviewed 1 of 39 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Gruntfile.js, line 323 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261#-Kd2c2l-fPMEF1z1G4h3:-Kd2fn1nJgVLrFOzp80t:b-egu91v) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/ddda34aca38ac3283ebadc9c1d2a43b5e11ddbea/Gruntfile.js#L323)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Alas, I'm afraid that's the case, unless we add new pug files for all existing *.tpl.html files.  Then we might be able to simplify things...
</blockquote></details>

Could we add a comment to that effect?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261#-:-Kd2g4iBcooQFuTeoliW:b-1oh89c)*

**Comment by StephenMcConnel** [comment]
Review status: 26 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[Gruntfile.js, line 323 at r1](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261#-Kd2c2l-fPMEF1z1G4h3:-Kd2kWEpDBIHofehZ62_:botlyxz) ([raw file](https://github.com/bloombooks/bloomlibrary/blob/ddda34aca38ac3283ebadc9c1d2a43b5e11ddbea/Gruntfile.js#L323)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Could we add a comment to that effect?
</blockquote></details>

Done.  Also added a comment at the clean: target where a similar list exists.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261)*

**Comment by andrew-polk** [comment]
This is a great improvement. Thanks!

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomlibrary/261#-:-Kd2ktKT5H5FWLSSRVHj:b-r1k3np)*

**Comment by hatton** [comment]
This is a good step, but it relies on individual files to be listed various places. So if a file is added/renamed, then the programmer has to figure out other files to make changes to. What would it take to get to a more wildcard approach?

**Pull request merged**
